### ISSUE TITLE
Install fails with a non-zero code: 128

### ISSUE THREAD

**Issue by paalex** [roblandry/addon-shinobi#2]
# Problem/Motivation

Can't install

## Expected behavior

Install succeeds

## Actual behavior

Install fails

## Steps to reproduce

Click install on hassio add-ons page after adding the repository following the official guide 

Home Assistant Core 0.111.1
Raspberry Pi 4b 64bit

Full error from Hassio log:

```
20-06-18 03:29:54 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/roblandry/addon-shinobi repository
20-06-18 03:30:02 INFO (MainThread) [supervisor.store] Load add-ons from store: 69 all - 1 new - 0 remove
20-06-18 03:31:05 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/7ed3b001_shinobi
20-06-18 03:31:05 INFO (SyncWorker_16) [supervisor.docker.addon] Start build 7ed3b001/armv7-addon-shinobi:0.4.0b3
20-06-18 03:41:40 INFO (MainThread) [supervisor.api.security] /snapshots access from 2c12253f_hassio_google_drive_backup
20-06-18 03:50:22 ERROR (SyncWorker_16) [supervisor.docker.addon] Can't build 7ed3b001/armv7-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 1
20-06-18 03:57:57 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-18 04:28:00 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-18 04:30:14 INFO (MainThread) [supervisor.host.info] Update local host information
20-06-18 04:30:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-06-18 04:30:14 INFO (MainThread) [supervisor.host.services] Update service information
20-06-18 04:30:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-06-18 04:30:14 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-06-18 04:30:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-06-18 04:30:15 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-06-18 04:41:41 INFO (MainThread) [supervisor.api.security] /snapshots access from 2c12253f_hassio_google_drive_backup
20-06-18 04:54:15 INFO (SyncWorker_16) [supervisor.docker.addon] Start build 7ed3b001/armv7-addon-shinobi:0.4.0b3
20-06-18 04:58:04 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-18 05:03:16 ERROR (SyncWorker_16) [supervisor.docker.addon] Can't build 7ed3b001/armv7-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 128
```

**Comment by Xplouder** [comment]
Similar problem:

```
20-08-01 00:03:56 INFO (SyncWorker_6) [supervisor.docker.addon] Start build 7ed3b001/armv7-addon-shinobi:0.4.0b3
20-08-01 00:07:31 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build 7ed3b001/armv7-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 1
20-08-01 00:07:31 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-39856' coro=<AddonManager.install() done, defined at /usr/src/supervisor/supervisor/addons/__init__.py:125> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 154, in install
    raise AddonsError() from None
supervisor.exceptions.AddonsError
```

**Comment by rradar** [comment]
Home Assistant 0.113.3 install on a x86_64 system fails too @roblandry :confused: 

![image](https://user-images.githubusercontent.com/34582688/89568884-db1c4100-d81b-11ea-9cb9-cf5dfe5b6400.png)

```yaml

20-08-06 18:26:50 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/7ed3b001_shinobi
20-08-06 18:26:50 INFO (SyncWorker_4) [supervisor.docker.addon] Start build 7ed3b001/amd64-addon-shinobi:0.4.0b3
20-08-06 18:33:45 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 7ed3b001/amd64-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 1
```

**Comment by corvy** [comment]
I tried the install and got the following error in my logs:

```
20-08-13 06:07:37 INFO (SyncWorker_2) [supervisor.docker.addon] Start build 7ed3b001/amd64-addon-shinobi:0.4.0b3
20-08-13 06:07:50 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build 7ed3b001/amd64-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 1
```

**Comment by roblandry** [comment]
Should be fixed in v0.4.0b4

**Comment by Xplouder** [comment]
@roblandry Just tried install and still got some errors:

![image](https://user-images.githubusercontent.com/2997254/94827506-6e2ebd00-0400-11eb-988c-c84122e3abec.png)

```
20-10-01 15:07:52 ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build 7ed3b001/armv7-addon-shinobi:0.4.0b3: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 3
20-10-01 15:07:52 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-119640' coro=<AddonManager.install() done, defined at /usr/src/supervisor/supervisor/addons/__init__.py:143> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 411, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         build-base=0.5-r1         g++=9.2.0-r4         jpeg-dev=8-r6         make=4.2.1-r2         openssl-dev=1.1.1g-r0         pkgconf=1.6.3-r0         python2-dev=2.7.18-r0         git=2.24.3-r0     && apk add --no-cache         npm=12.15.0-r1         yarn=1.19.2-r0         ffmpeg=4.2.1-r3         mysql-client=10.4.13-r0         nodejs=12.15.0-r1         python2=2.7.18-r0         socat=1.7.3.3-r1         sqlite=3.30.1-r2         ttf-freefont=20120503-r1         x264=20191119-r0         x265=3.2.1-r0     && git clone -b master --single-branch         https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi/     && git -C /opt/shinobi checkout 3f536cc1c6c616029f4a8a83c48356cb934979e9     && git -C /opt/shinobi reflog expire --expire=now --all     && git -C /opt/shinobi gc --prune=now --aggressive     && cd /opt/shinobi     && yarn add mysql sqlite3     && yarn install     && apk del --purge .build-dependencies' returned a non-zero code: 3
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 169, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 398, in _install
    self._build(tag)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 422, in _build
    raise DockerError() from err
supervisor.exceptions.DockerError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 172, in install
    raise AddonsError() from err
supervisor.exceptions.AddonsError
```

**Comment by roblandry** [comment]
You need to refresh the addons. Having the pinned versions tells me it didn't update. Ie "build-base=0.5-r1"
Should be version 0.4.0b4

**Comment by Xplouder** [comment]
Reloaded the addons and reinstalled the repository but still got exactly the same error but not with the correct version:
```
ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 7ed3b001/armv7-addon-shinobi:0.4.0b4
...
```
